#pragma once

// see https://github.com/geanix/courgette/blob/master/gen/base/partition_alloc_buildflags.h
// see https://github.com/chromium/chromium/blob/master/base/BUILD.gn#L2037

// Generated by build/write_buildflag_header.py
// From "//base:partition_alloc_buildflags"

#include "build/buildflag.h"

#if defined(WIN32) || defined(WIN64)
#define BUILDFLAG_INTERNAL_USE_PARTITION_ALLOC() (1)
#else
#define BUILDFLAG_INTERNAL_USE_PARTITION_ALLOC() (0)
#endif
