# see component("base") in BUILD.gn
list(APPEND COMPONENT_BASE_SOURCES_ANDROID_UNPROCESSED
  "debug/stack_trace_android.cc"
  "files/file_util_android.cc"
  "files/scoped_file_android.cc"
  "message_loop/message_pump_android.cc"
  "message_loop/message_pump_android.h"
  "os_compat_android.cc"
  "os_compat_android.h"
  "process/process_android.cc"
  "profiler/stack_sampler_android.cc"
  "threading/platform_thread_android.cc"
)

list(APPEND COMPONENT_BASE_SOURCES_ANDROID_UNPROCESSED
  "android/android_hardware_buffer_compat.cc"
  "android/android_hardware_buffer_compat.h"
  "android/android_image_reader_abi.h"
  "android/android_image_reader_compat.cc"
  "android/android_image_reader_compat.h"
  "android/apk_assets.cc"
  "android/apk_assets.h"
  "android/application_status_listener.cc"
  "android/application_status_listener.h"
  "android/base_jni_onload.cc"
  "android/base_jni_onload.h"
  "android/build_info.cc"
  "android/build_info.h"
  "android/bundle_utils.cc"
  "android/bundle_utils.h"
  "android/callback_android.cc"
  "android/callback_android.h"
  "android/child_process_binding_types.h"
  "android/child_process_service.cc"
  "android/command_line_android.cc"
  "android/content_uri_utils.cc"
  "android/content_uri_utils.h"
  "android/cpu_features.cc"
  "android/early_trace_event_binding.cc"
  "android/early_trace_event_binding.h"
  "android/event_log.cc"
  "android/event_log.h"
  "android/feature_list_jni.cc"
  "android/field_trial_list.cc"
  "android/important_file_writer_android.cc"
  "android/int_string_callback.cc"
  "android/int_string_callback.h"
  "android/java_exception_reporter.cc"
  "android/java_exception_reporter.h"
  "android/java_handler_thread.cc"
  "android/java_handler_thread.h"
  "android/java_heap_dump_generator.cc"
  "android/java_heap_dump_generator.h"
  "android/java_runtime.cc"
  "android/java_runtime.h"
  "android/jni_android.cc"
  "android/jni_android.h"
  "android/jni_array.cc"
  "android/jni_array.h"
  "android/jni_generator/jni_generator_helper.h"
  "android/jni_int_wrapper.h"
  "android/jni_registrar.cc"
  "android/jni_registrar.h"
  "android/jni_string.cc"
  "android/jni_string.h"
  "android/jni_utils.cc"
  "android/jni_utils.h"
  "android/jni_weak_ref.cc"
  "android/jni_weak_ref.h"
  "android/library_loader/anchor_functions.cc"
  "android/library_loader/anchor_functions.h"
  "android/library_loader/library_loader_hooks.cc"
  "android/library_loader/library_loader_hooks.h"
  "android/library_loader/library_prefetcher.cc"
  "android/library_loader/library_prefetcher.h"
  "android/library_loader/library_prefetcher_hooks.cc"
  "android/locale_utils.cc"
  "android/locale_utils.h"
  "android/memory_pressure_listener_android.cc"
  "android/memory_pressure_listener_android.h"
  "android/native_uma_recorder.cc"
  "android/path_service_android.cc"
  "android/path_utils.cc"
  "android/path_utils.h"
  "android/radio_utils.cc"
  "android/radio_utils.h"
  "android/reached_addresses_bitset.cc"
  "android/reached_addresses_bitset.h"
  "android/reached_code_profiler.cc"
  "android/reached_code_profiler.h"
  "android/record_histogram.cc"
  "android/record_user_action.cc"
  "android/scoped_hardware_buffer_fence_sync.cc"
  "android/scoped_hardware_buffer_fence_sync.h"
  "android/scoped_hardware_buffer_handle.cc"
  "android/scoped_hardware_buffer_handle.h"
  "android/scoped_java_ref.cc"
  "android/scoped_java_ref.h"
  "android/statistics_recorder_android.cc"
  "android/sys_utils.cc"
  "android/sys_utils.h"
  "android/task_scheduler/post_task_android.cc"
  "android/task_scheduler/post_task_android.h"
  "android/task_scheduler/task_runner_android.cc"
  "android/task_scheduler/task_runner_android.h"
  "android/time_utils.cc"
  "android/timezone_utils.cc"
  "android/timezone_utils.h"
  "android/trace_event_binding.cc"
  "android/trace_event_binding.h"
  "android/unguessable_token_android.cc"
  "android/unguessable_token_android.h"
  "memory/platform_shared_memory_region_android.cc"
  "system/sys_info_android.cc"
  # Android uses some Linux sources.
  "debug/elf_reader.cc"
  "debug/elf_reader.h"
  "debug/proc_maps_linux.cc"
  "debug/proc_maps_linux.h"
  "files/file_path_watcher_linux.cc"
  "power_monitor/power_monitor_device_source_android.cc"
  "process/internal_linux.cc"
  "process/internal_linux.h"
  "process/memory_linux.cc"
  "process/process_handle_linux.cc"
  "process/process_iterator_linux.cc"
  "process/process_metrics_linux.cc"
  "system/sys_info_linux.cc"
)

if (can_unwind_with_cfi_table) {
  list(APPEND COMPONENT_BASE_SOURCES_ANDROID_UNPROCESSED
    "trace_event/cfi_backtrace_android.cc"
    "trace_event/cfi_backtrace_android.h"
  )
endif(can_unwind_with_cfi_table)

if (TARGET_ARM) {
  list(APPEND COMPONENT_BASE_SOURCES_ANDROID_UNPROCESSED
    "profiler/chrome_unwinder_android.cc"
    "profiler/chrome_unwinder_android.h"
  )
endif()

if (NOT TARGET_ARM AND NOT TARGET_ARM64) {
  # The reached code profiler is only supported on Android arm arch.
  list(APPEND COMPONENT_BASE_SOURCES_ANDROID_UNPROCESSED
   "android/reached_code_profiler_stub.cc"
  )
endif()

list(APPEND COMPONENT_BASE_SOURCES ${COMPONENT_BASE_SOURCES_ANDROID_UNPROCESSED})
